security:

    providers:
        in_memory:
            memory: ~

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_secured:
            pattern:  ^/secure 
            stateless: true
            custom_security: true
            methods: [GET, POST, PUT, DELETE]
            
        logout_secured:
            pattern:  ^/logout 
            stateless: true
            custom_security: true
            methods: [POST]
