<?php 

namespace Bundles\ProductBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CategoryRepository extends EntityRepository
{
	
	public function getCategory($limit = null, $boolReturnArray = true )
	{
		$qb = $this->createQueryBuilder('b')
		->select('b');
	
		if (false === is_null($limit))
			$qb->setMaxResults($limit);
		if( $boolReturnArray ) return $qb->getQuery()->getResult( Query::HYDRATE_ARRAY );
		
		return $qb->getQuery()->getResult();
	}
}