<?php 

namespace Bundles\ProductBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ProductRepository extends EntityRepository
{
	
	public function getProducts($limit = null, $boolReturnArray = true )
	{
		$qb = $this->createQueryBuilder('b')
			->select('b');
		if (false === is_null($limit))
			$qb->setMaxResults($limit);
		
		if (false === is_null($limit))
			$qb->setMaxResults($limit);

		if( $boolReturnArray ) return $qb->getQuery()->getResult( Query::HYDRATE_ARRAY );
		
		return $qb->getQuery()->getResult();
	}
	
	public function getProductsByCategoryId( $id ) {
		$qb = $this->createQueryBuilder('b')
		->select('b')
		->where('b.category_id = :id')
		->setParameter('id', $id);

		return $qb->getQuery()->getResult( Query::HYDRATE_ARRAY );
		
	}
	
	public function getDetails( $id ) {
		$qb = $this->createQueryBuilder('p')
			->select('p')
			->where( 'p.id = :id' )
			->setParameter('id', $id);
		
		return $qb->getQuery()->getOneOrNullResult( Query::HYDRATE_ARRAY );
		
	}
	

}