<?php
namespace Bundles\OrderBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class OrderItemsRepository extends EntityRepository
{

	public function fetchOrderItemsByOrderId( $intOrderId, $boolIsReturnArray = false ) {
	
		$qb = $this->createQueryBuilder('oi')
		->select('oi')
		->join( 'oi.orders', 'o' )
		->where( 
				'o.id = :order_id' )
		->setParameters(
			array(
				'order_id' => $intOrderId
			)
		);

		if( true == $boolIsReturnArray )  {
			return $qb->getQuery()->getResult( Query::HYDRATE_ARRAY );
		}

		return $qb->getQuery()->getResult();
	}
	
}