bundles_order_default:
    type: rest
    prefix: /secure
    resource: "Bundles\\OrderBundle\\Controller\\OrderController"

bundles_payment_default:
    type: rest
    prefix: /secure
    resource: "Bundles\\OrderBundle\\Controller\\PaymentController"

bundles_syncdb_default:
    type: rest
    prefix: /
    resource: "Bundles\\OrderBundle\\Controller\\SyncDatabaseController"